name: Backend Tests

# Dispara sempre que houver push ou PR na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Roda os testes do backend
      - name: Run backend tests
        run: pytest --maxfail=1 --disable-warnings -q
