name: Backend Tests

# Dispara sempre que houver push ou PR na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Importante: roda dentro da pasta backend
    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Roda os testes com cobertura
      - name: Run backend tests with coverage
        run: |
          python -m pytest --maxfail=1 --disable-warnings --cov=backend --cov-report=xml --cov-report=html

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: backend/coverage.xml
      
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov

